config_version = "0"

exclude_patterns = [
  "*_min.*", "*-min.*", "*.min.*", "**/.yarn/**", "**/*.d.ts",
  "**/assets/**", "**/bower_components/**", "**/build/**", "**/cache/**",
  "**/config/**", "**/db/**", "**/deps/**", "**/dist/**", "**/extern/**",
  "**/external/**", "**/generated/**", "**/Godeps/**", "**/gradlew/**",
  "**/mvnw/**", "**/node_modules/**", "**/protos/**", "**/seed/**",
  "**/target/**", "**/templates/**", "**/testdata/**", "**/vendor/**",
  "**/.next/**", "**/*.pyc", "**/*.lock", "**/go.sum", "**/go.mod",
  "**/Podfile.lock", "**/yarn.lock", "**/package-lock.json", "**/Dockerfile*",
  "**/*.svg", "**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.ico",
  "**/*.woff", "**/*.woff2", "**/*.ttf", "**/*.txt", "**/*.md", "**/*.json",
  "*/*.yml", "**/*.yaml", "**/*.ini", "**/*.toml", "**/*.lock", "**/*.pyi",
  "**/*.bin", "**/*.exe", "**/*.dll", "**/*.so", "**/*.lo"
]

test_patterns = [
  "**/test/**", "**/spec/**", "**/*.test.*", "**/*.spec.*",
  "**/*_test.*", "**/*_spec.*", "**/test_*.*", "**/spec_*.*"
]

[smells]
mode = "comment"  # report codeâ€‘smell issues, do not block

[[source]]
name = "default"
default = true


# Disable linters to avoid lint suggestions
[[plugin]]
name = "eslint"
version = "9.39.1"
package_file = "node_tools/package.json"
package_filters = ["eslint"]
mode = "disabled"

[[plugin]]
name = "biome"
mode = "disabled"

[[plugin]]
name = "radarlint-js"
mode = "disabled"

[[plugin]]
name = "radarlint-python"
mode = "disabled"

[[plugin]]
name = "ruff"
mode = "disabled"

# Security scanners
[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "ripgrep"
mode = "comment"

[[plugin]]
name = "trivy"
drivers = ["config", "fs-vuln"]

[[plugin]]
name = "trufflehog"
